#!/usr/bin/env python3

import json
import os
import sys

from shutil import copyfileobj


def main():
    tmpdir = os.environ['PYTEST_TMPDIR']
    with open(os.path.join(tmpdir, 'sendmail.args'), 'w') as f:
        json.dump(sys.argv, f, indent=2)
    with open(os.path.join(tmpdir, 'sendmail.input'), 'w') as f:
        copyfileobj(sys.stdin, f)


if __name__ == '__main__':
    main()
